feather_data_dir: "/Users/jiguangli/Dropbox/ir_data_clean"
model_output_dir: "/Users/jiguangli/item_response/model_output"
linked_data_dir: "/Users/jiguangli/Dropbox/linked_anonymized_MCAS_data"
linked_data_processed_dir: "/Users/jiguangli/Dropbox/linked_mcas_data_processed"

exam_types:
  18_10_m_labels:
    number_and_quantity: [1,2,6,10, 13, 15, 17, 30, 37]
    geometry: [3,8, 12, 18, 24, 26, 27, 32, 34, 36, 39, 42]
    algebra_and_function: [4,5,9,14,19,20,21,22,23, 28, 31, 38]
    stats: [7,11, 16, 25, 29, 33, 35, 40, 41]